clean_runs:
    name: 清理历史运行记录
    runs-on: ubuntu-latest
    needs: sync
    steps:
      - name: 清理工作流运行记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 0
